version: '3'
services:
  proxy:
    image: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - '8080:80'
    depends_on:
      - accounts
      - admin
      - channels
      - common
      - consents
      - credit-cards-accounts
      - customers
      - financings
      - invoice-financings
      - loans
      - participants
      - products-services
      - unarranged-accounts-overdraft
  accounts:
    image: stoplight/prism:4
    command: >
      mock -p 4010 --host 0.0.0.0
      https://raw.githubusercontent.com/OpenBanking-Brasil/areadesenvolvedor-fase2/gh-pages/swagger/swagger_accounts_apis.yaml
  admin:
    image: stoplight/prism:4
    command: >
      mock -p 4010 --host 0.0.0.0
      https://raw.githubusercontent.com/OpenBanking-Brasil/areadesenvolvedor/master/documentation/source/swagger/swagger_admin_apis.yaml
  channels:
    image: stoplight/prism:4
    command: >
      mock -p 4010 --host 0.0.0.0
      https://raw.githubusercontent.com/OpenBanking-Brasil/areadesenvolvedor/master/documentation/source/swagger/swagger_channels_apis.yaml
  common:
    image: stoplight/prism:4
    command: >
      mock -p 4010 --host 0.0.0.0
      https://raw.githubusercontent.com/OpenBanking-Brasil/areadesenvolvedor/master/documentation/source/swagger/swagger_common_apis.yaml
  consents:
    image: stoplight/prism:4
    command: >
      mock -p 4010 --host 0.0.0.0
      https://raw.githubusercontent.com/OpenBanking-Brasil/areadesenvolvedor-fase2/gh-pages/swagger/swagger_consents.yaml
  credit-cards-accounts:
    image: stoplight/prism:4
    command: >
      mock -p 4010 --host 0.0.0.0
      https://raw.githubusercontent.com/OpenBanking-Brasil/areadesenvolvedor-fase2/gh-pages/swagger/swagger_credit_cards_apis.yaml
  customers:
    image: stoplight/prism:4
    command: >
      mock -p 4010 --host 0.0.0.0
      https://raw.githubusercontent.com/OpenBanking-Brasil/areadesenvolvedor-fase2/gh-pages/swagger/swagger_customers_apis.yaml
  financings:
    image: stoplight/prism:4
    command: >
      mock -p 4010 --host 0.0.0.0
      https://raw.githubusercontent.com/OpenBanking-Brasil/areadesenvolvedor-fase2/gh-pages/swagger/swagger_financings_apis.yaml
  invoice-financings:
    image: stoplight/prism:4
    command: >
      mock -p 4010 --host 0.0.0.0
      https://raw.githubusercontent.com/OpenBanking-Brasil/areadesenvolvedor-fase2/gh-pages/swagger/swagger_invoice_financings_apis.yaml
  loans:
    image: stoplight/prism:4
    command: >
      mock -p 4010 --host 0.0.0.0
      https://raw.githubusercontent.com/OpenBanking-Brasil/areadesenvolvedor-fase2/gh-pages/swagger/swagger_loans_apis.yaml
  participants:
    image: stoplight/prism:4
    command: >
      mock -p 4010 --host 0.0.0.0
      https://raw.githubusercontent.com/OpenBanking-Brasil/areadesenvolvedor-fase2/gh-pages/swagger/swagger_participants.yaml
  products-services:
    image: stoplight/prism:4
    command: >
      mock -p 4010 --host 0.0.0.0
      https://raw.githubusercontent.com/OpenBanking-Brasil/areadesenvolvedor/master/documentation/source/swagger/swagger_products_services_apis.yaml
  unarranged-accounts-overdraft:
    image: stoplight/prism:4
    command: >
      mock -p 4010 --host 0.0.0.0
      https://raw.githubusercontent.com/OpenBanking-Brasil/areadesenvolvedor-fase2/gh-pages/swagger/swagger_unarranged_accounts_overdraft_apis.yaml